feat: Refactor to integration testing setup (SC-567)
marsfoundation/spark-alm-controller pull request #7
Opened 2024-08-08 17:51 UTC by lucas-manuel

2024-08-12 13:15 UTC, lucas-manuel commented on test/fork/ForkTestBase.t.sol
> +    uint256 constant INK = 1e12 * 1e18;  // Ink initialization amount
Its used in the inheriting VaultCalls contract assertions

2024-08-12 13:17 UTC, lucas-manuel commented on test/fork/ForkTestBase.t.sol
> +    bytes32 constant RELAYER    = keccak256("RELAYER");
Updated

2024-08-12 19:33 UTC, hexonaut requested changes
A few issues. `MockJug` is unused. Also, I noticed `ALMProxy` is missing a way to send ETH to it. It should have a `receive()` special function.

Not sure why CI is failing, but tests work locally.

2024-08-12 19:33 UTC, hexonaut commented on test/unit/UnitTestBase.t.sol
> +        almProxy.grantRole(FREEZER,    freezer);
ALM Proxy does not have a freezer role.

2024-08-12 20:44 UTC, lucas-manuel commented on src/EthereumController.sol
> +        uint256 wadAmount = usdcAmount * psm.to18ConversionFactor();
Updated

2024-08-12 20:44 UTC, lucas-manuel commented on src/EthereumController.sol
> +        uint256 wadAmount = usdcAmount * psm.to18ConversionFactor();
Updated

2024-08-12 20:50 UTC, lucas-manuel commented on test/fork/ForkTestBase.t.sol
> +            duty           : 1000000001243680656318820312,
Updated

2024-08-12 20:50 UTC, lucas-manuel commented on test/fork/ForkTestBase.t.sol
> +            ttl            : 1 days,
Updated

2024-08-12 20:50 UTC, lucas-manuel commented on test/fork/ForkTestBase.t.sol
> +        almProxy.grantRole(FREEZER,    freezer);
Fixed

2024-08-12 20:50 UTC, lucas-manuel commented on test/unit/UnitTestBase.t.sol
> +        almProxy.grantRole(FREEZER,    freezer);
Fixed

2024-08-13 14:58 UTC, hexonaut approved these changes

2024-08-13 15:00 UTC, merged